sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t tlzzs/docker-react .

script:
  - docker run -e CI=true tlzzs/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-836970978192"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"